pcwd/feed/urls.py
from django.urls import path
from .views import PostListView, PostCreateView


app_name = 'feed'

urlpatterns = [
    path('en/', PostListView.as_view(), name='post-list-en'),
    path('ar/', PostListView.as_view(), name='post-list-ar'),
    path('en/post_form/', PostCreateView.as_view(), name='post-create-en'),
    path('ar/post_form/', PostCreateView.as_view(), name='post-create-ar'),
]

pcwd/user/urls.py
from django.urls import path
from .views import add_to_favorite, remove_from_favorite, favorites_list


app_name = 'user'

urlpatterns = [
    path('en/add-to-favorite/<int:product_id>/', add_to_favorite, name='add-to-favorite-en'),
    path('ar/add-to-favorite/<int:product_id>/', add_to_favorite, name='add-to-favorite-ar'),
    path('en/remove-from-favorite/<int:product_id>/', remove_from_favorite, name='remove-from-favorite-en'),
    path('ar/remove-from-favorite/<int:product_id>/', remove_from_favorite, name='remove-from-favorite-ar'),
    path('en/', favorites_list, name='favorites-list-en'),
    path('ar/', favorites_list, name='favorites-list-ar'),
]

pcwd/feed/models.py
"""
Post model for the feed app.
"""

from django.db import models
from django.conf import settings


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.content[:30]}'

pcwd/feed/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin


# listView to display all the posts
class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 10

    def get_template_names(self):
        if 'en' in self.request.path:
            return ['feed_en.html']
        elif 'ar' in self.request.path:
            return ['feed_ar.html']
        else:
            return ['feed_en.html']


# createView to handle post submissions
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['content']
    success_url = reverse_lazy('feed:post-list')

    def get_template_names(self):
        if 'en' in self.request.path:
            return ['post_form_en.html']
        elif 'ar' in self.request.path:
            return ['post_form_ar.html']
        else:
            return ['post_form_en.html']

    def get_success_url(self):
        if 'en' in self.request.path:
            return reverse_lazy('feed:post-list-en')
        elif 'ar' in self.request.path:
            return reverse_lazy('feed:post-list-ar')
        else:
            return reverse_lazy('feed:post-list-en')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

pcwd/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}

<html lang="{% get_current_language %}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock head_title %}</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/mintcircle.ico' %}">

    <!-- Preconnect for Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap" rel="stylesheet">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block extra_head %}
    <!-- Additional styles or scripts can be added here -->
    {% endblock extra_head %}
</head>
<body>
    <header class="site-header">
        <nav class="menu">
            <img src="{% static 'images/mintcircle.png' %}" alt="Favicon" class="menu-favicon">
            <a href="{% url 'home' %}" class="menu-item">{% trans "Home" %}</a>
            <a href="{% url 'account_login' %}" class="menu-item">{% trans "My Account" %}</a>
        </nav>
    </header>

    {% block body %}
        {% if messages %}
            <div class="message-container">
                <strong>{% trans "Messages:" %}</strong>
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="container">
            {% block content %}
            <!-- Page-specific content will go here -->
            {% endblock content %}
        </div>
    {% endblock body %}

    <footer class="site-footer">
        <!-- Optional footer content -->
    </footer>

    {% block extra_body %}
    <!-- Additional scripts can be added here -->
    {% endblock extra_body %}

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

pcwd/templates/favorites_list_ar.html
<!DOCTYPE html>
{% load static %}
{% load custom_filters %}
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>المفضلات الخاصة بك - مقارنة الساعات الذكية</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/mintcircle.ico' %}">

    <!-- Preconnect for Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa&family=Noto+Kufi+Arabic:wght@100..900&display=swap" rel="stylesheet">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">

    <!-- Meta Tags for SEO -->
    <meta name="description" content="استعرض ساعاتك الذكية المفضلة وقارن بينها بسهولة.">
    <meta name="keywords" content="المفضلات, الساعات الذكية, مقارنة الساعات الذكية">
    <link rel="canonical" href="{{ request.build_absolute_uri }}">

    <!-- Open Graph Meta Tags for Social Media -->
    <meta property="og:title" content="المفضلات الخاصة بك - مقارنة الساعات الذكية">
    <meta property="og:description" content="استعرض ساعاتك الذكية المفضلة وقارن بينها بسهولة.">
    <meta property="og:image" content="{% static 'images/pcwd-image-2.png' %}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="مقارنة الساعات الذكية">
    <meta property="og:locale" content="ar_AR">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="المفضلات الخاصة بك - مقارنة الساعات الذكية">
    <meta name="twitter:description" content="استعرض ساعاتك الذكية المفضلة وقارن بينها بسهولة.">
    <meta name="twitter:image" content="{% static 'images/pcwd-image-2.png' %}">

</head>
<body class="noto-kufi-arabic">
    <header class="site-header">
        <nav class="menu">
            <a href="{% url 'feed:post-list-ar' %}" title="انقر لكتابة منشور">
                <img src="{% static 'images/mintcircle.png' %}" alt="Favicon" class="menu-favicon">
            </a>
            <a href="{% url 'home' %}" class="menu-item">الصفحة الرئيسية</a>
            <a href="#" class="menu-item" data-modal="modal3">عن الموقع</a>
            <a href="#" class="menu-item" data-modal="modal4">اتصل بنا</a>
            {% if user.is_authenticated %}
                <a href="#" class="menu-item" data-modal="modal-account">
                    <img src="{{ user.profile.image.url }}" alt="{{ user.username }} صورة الملف الشخصي" class="menu-profile-image">
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class="menu-item">حسابي</a>
            {% endif %}
        </nav>
    </header>

    <div class="container">
        <h1 style="font-size: 1.5em; text-align: center;">ساعاتك الذكية المفضلة</h1>
        {% if not favorites %}
            <p>ليس لديك أي منتجات مفضلة بعد.</p>
        {% else %}
            <div class="product-grid">
                {% for product in favorites %}
                    <div class="product-card" data-url="{{ product.image_url }}">
                        <div class="product-image">
                            <img src="{{ product.image.url }}" alt="{{ product.description }}">
                            <div class="product-info">
                                <p class="description">{{ product.description }}</p>
                                {% if product.price %}
                                    <p class="price">{{ product.price }} {{ product.currency }}</p>
                                {% endif %}

                                <!-- Star button for favorites -->
                                <form method="post" action="{% url 'user:remove-from-favorite-ar' product.id %}">
                                    {% csrf_token %}
                                     <button type="submit" class="favorites-button" title="إزالة من المفضلة">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="red">
                                            <path d="M19.41 4.59a1 1 0 0 0-1.42 0L12 10.58 6.01 4.59A1 1 0 0 0 4.59 6.01L10.58 12 4.59 17.99a1 1 0 1 0 1.42 1.42L12 13.42l5.99 5.99a1 1 0 0 0 1.42-1.42L13.42 12l5.99-5.99a1 1 0 0 0 0-1.42z" stroke="red" stroke-width="2"/>
                                        </svg>
                                     </button>
                                </form>

                                <div class="button-container">
                                    <form method="get" action="{% url 'fetch-recommended-products-ar' %}">
                                        <input type="hidden" name="product_id" value="{{ product.id }}">
                                        <button type="submit" class="visit-store-button also-button also-ar" title="توصيات">أيضًا</button>
                                    </form>
                                    <a class="visit-store-button store-ar" href="{{ product.product_url }}" target="_blank">المتجر</a>
                                </div>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <!-- Additional Modals -->
    <div id="modal3" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="margin-top: 50px;">
                مرحبًا بكم في <span style="color: #014421; font-weight: bold;">fromsifr.com</span> !
            </p>
            <p>
                في هذا الإصدار الأول، نقدم مجموعة واسعة من الساعات الذكية من عدة مواقع. <br>
                قريبًا، سنضيف الساعات التقليدية وميزات جديدة...
            </p>
        </div>
    </div>

    <div id="modal4" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="margin-top: 50px;">
                نريد الحصول على ملاحظاتكم!
            </p>
            <p>
                هل لديكم أفكار أو طلبات ميزات؟ <br> هل ترغبون في رؤية منتجات إضافية أو حتى ميزات الشراء والبيع؟<br> نقدر آرائكم ونود سماعها! <br>
                 يرجى مراسلتنا على <strong>medlao.contact@gmail.com</strong><br> أو خذوا لحظة لكتابة منشور لمشاركة ملاحظاتكم.
            </p>
            <p>
                شكرًا لمساعدتكم في تحسين تجربتنا!
            </p>
        </div>
    </div>

    <div id="modal-account" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <img src="{{ user.profile.image.url }}" alt="{{ user.username }} صورة الملف الشخصي" class="profile-image">
            <p id="username">{{ user.username }}</p>
            <p class="email-address">{{ user.email }}</p>
            <ul class="provider-list">
                <li class="provider-item"><a href="{% url 'user:favorites-list-ar' %}" class="provider-link">المفضلات الخاصة بي</a></li>
                <li class="provider-item"><a href="{% url 'account_logout' %}" class="provider-link">تسجيل الخروج</a></li>
                <li class="provider-item"><a href="{% url 'account_change_password' %}" class="provider-link">تغيير كلمة المرور</a></li>
                <li class="provider-item"><a href="{% url 'account_email' %}" class="provider-link">إدارة البريد الإلكتروني</a></li>
            </ul>
        </div>
    </div>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

pcwd/templates/feed_ar.html
<!DOCTYPE html>
{% load static %}
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>التغذية</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/mintcircle.ico' %}">

    <!-- Preconnect for Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- Google Fonts for English (Nunito) and Arabic (Noto Kufi Arabic) -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@400;700&display=swap" rel="stylesheet">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/feed.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">
</head>
<body class="noto-kufi-arabic">

    <!-- Header and Menu -->
    <header class="site-header">
        <nav class="menu">
            <a href="{% url 'feed:post-list-ar' %}" title="انقر لكتابة منشور">
                <img src="{% static 'images/mintcircle.png' %}" alt="Favicon" class="menu-favicon">
            </a>
            <a href="{% url 'home' %}" class="menu-item">الصفحة الرئيسية</a>
            <a href="#" class="menu-item" data-modal="modal3">عن الموقع</a>
            <a href="#" class="menu-item" data-modal="modal4">اتصل بنا</a>
            {% if user.is_authenticated %}
                <a href="#" class="menu-item" data-modal="modal-account">
                    <img src="{{ user.profile.image.url }}" alt="{{ user.username }} صورة الملف الشخصي" class="menu-profile-image">
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class="menu-item">حسابي</a>
            {% endif %}
        </nav>
    </header>

    <div class="container">
        <h1 class="center-title">شاركوا ملاحظاتكم أو أفكاركم</h1>
        {% if user.is_authenticated %}
            <a href="{% url 'feed:post-create-ar' %}" class="button center-button">اكتب منشوراً</a>
        {% else %}
            <p class="login-prompt">سجل الدخول لكتابة منشور</p>
        {% endif %}

        <div class="post-grid">
            {% if posts %}
                {% for post in posts %}
                    <div class="post-card">
                        <div class="post-content">
                            <p>كتبه <span style="color: #01796F; font-weight: bold;">{{ post.user.username }}</span></p>
                            <p dir="auto">{{ post.content }}</p>
                            <small dir="ltr">{{ post.created_at }}</small>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>لا توجد ملاحظات بعد. كن أول من يكتب شيئاً!</p>
            {% endif %}
        </div>

        <!-- Include the pagination snippet -->
        {% include 'pagination_ar.html' %}
    </div>

    <div id="modal3" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="margin-top: 50px;">
                مرحبًا بكم في <span style="color: #014421; font-weight: bold;">fromsifr.com</span> !
            </p>
            <p>
                في هذا الإصدار الأول، نقدم مجموعة واسعة من الساعات الذكية من عدة مواقع. <br>
                قريباً، سنضيف ساعات تقليدية وسنقوم بإدخال ميزات جديدة...
            </p>
        </div>
    </div>

    <div id="modal4" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="margin-top: 50px;">
                نريد الحصول على ملاحظاتكم!
            </p>
            <p>
                هل لديكم أفكار أو طلبات ميزات؟ <br> هل ترغبون في رؤية منتجات إضافية أو حتى ميزات الشراء والبيع؟<br> نقدر آرائكم ونود سماعها! <br>
                 يرجى مراسلتنا على <strong>medlao.contact@gmail.com</strong><br> أو خذوا لحظة لكتابة منشور لمشاركة ملاحظاتكم.
            </p>
            <p>
                شكرًا لمساعدتكم في تحسين تجربتنا!
            </p>
        </div>
    </div>

    <div id="modal-account" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <img src="{{ user.profile.image.url }}" alt="{{ user.username }} صورة الملف الشخصي" class="profile-image">
            <p id="username">{{ user.username }}</p>
            <p class="email-address">{{ user.email }}</p>
            <ul class="provider-list">
                <li class="provider-item"><a href="{% url 'user:favorites-list-ar' %}" class="provider-link">المفضلات الخاصة بي</a></li>
                <li class="provider-item"><a href="{% url 'account_logout' %}" class="provider-link">تسجيل الخروج</a></li>
                <li class="provider-item"><a href="{% url 'account_change_password' %}" class="provider-link">تغيير كلمة المرور</a></li>
                <li class="provider-item"><a href="{% url 'account_email' %}" class="provider-link">إدارة البريد الإلكتروني</a></li>
            </ul>
        </div>
    </div>

    <!-- Script Tag -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/feed.js' %}"></script>
</body>
</html>

pcwd/templates/pagination_ar.html
{% load custom_filters %}
<div class="pagination" style="direction: rtl;">
    <ul class="pagination-list">
        {% if page_obj.has_previous %}
            <li class="pagination-item">
                <a href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if max_price %}max_price={{ max_price }}{% endif %}&page=1" class="pagination-link">&laquo; الأول</a>
            </li>
            <li class="pagination-item">
                <a href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if max_price %}max_price={{ max_price }}{% endif %}&page={{ page_obj.previous_page_number }}" class="pagination-link">السابق</a>
            </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="pagination-item active">
                    <span class="pagination-link">{{ i }}</span>
                </li>
            {% elif i > page_obj.number|add:"-3" and i < page_obj.number|add:"3" %}
                <li class="pagination-item">
                    <a href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if max_price %}max_price={{ max_price }}{% endif %}&page={{ i }}" class="pagination-link">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="pagination-item">
                <a href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if max_price %}max_price={{ max_price }}{% endif %}&page={{ page_obj.next_page_number }}" class="pagination-link">التالي</a>
            </li>
            <li class="pagination-item">
                <a href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if max_price %}max_price={{ max_price }}{% endif %}&page={{ paginator.num_pages }}" class="pagination-link">الأخير &raquo;</a>
            </li>
        {% endif %}
    </ul>
</div>

pcwd/templates/product_list_ar.html
<!DOCTYPE html>
{% load static %}
{% load custom_filters %}
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>قائمة المنتجات - مقارنة الساعات الذكية</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/mintcircle.ico' %}">

    <!-- Preconnect for Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa&family=Noto+Kufi+Arabic:wght@100..900&display=swap" rel="stylesheet">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">

    <!-- Meta Tags for SEO -->
    <meta name="description" content="استعرض قائمة المنتجات وقارن بين أفضل الساعات الذكية المتوفرة. اعثر على الساعة الذكية المثالية لك.">
    <meta name="keywords" content="قائمة المنتجات, الساعات الذكية, مقارنة الساعات الذكية, أفضل الأسعار, شراء الساعات الذكية">
    <link rel="canonical" href="{{ request.build_absolute_uri }}">

    <!-- Open Graph Meta Tags for Social Media -->
    <meta property="og:title" content="قائمة المنتجات - مقارنة الساعات الذكية">
    <meta property="og:description" content="استعرض قائمة المنتجات وقارن بين أفضل الساعات الذكية المتوفرة. اعثر على الساعة الذكية المثالية لك.">
    <meta property="og:image" content="{% static 'images/pcwd-image-2.png' %}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="مقارنة الساعات الذكية">
    <meta property="og:locale" content="ar_AR">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="قائمة المنتجات - مقارنة الساعات الذكية">
    <meta name="twitter:description" content="استعرض قائمة المنتجات وقارن بين أفضل الساعات الذكية المتوفرة. اعثر على الساعة الذكية المثالية لك.">
    <meta name="twitter:image" content="{% static 'images/pcwd-image-2.png' %}">

</head>
<body class="noto-kufi-arabic">
    <header class="site-header">
        <nav class="menu menu-arabic">
            <a href="{% url 'feed:post-list-ar' %}" title="انقر لكتابة منشور">
                <img src="{% static 'images/mintcircle.png' %}" alt="Favicon" class="menu-favicon">
            </a>
            <a href="{% url 'home' %}" class="menu-item">الصفحة الرئيسية</a>
            <a href="#" class="menu-item" data-modal="modal2">البحث</a>
            <a href="#" class="menu-item" data-modal="modal3">عن الموقع</a>
            <a href="#" class="menu-item" data-modal="modal4">اتصل بنا</a>
            {% if user.is_authenticated %}
                <a href="#" class="menu-item" data-modal="modal-account">
                    <img src="{{ user.profile.image.url }}" alt="{{ user.username }} صورة الملف الشخصي" class="menu-profile-image">
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class="menu-item">حسابي</a>
            {% endif %}
        </nav>
    </header>

    <div class="container">
        {% if not products %}
            <p>عذرًا، لم يتم العثور على منتجات لطلب البحث الخاص بك.</p>
        {% else %}
            <div class="product-grid">
                {% for product in products %}
                    <div class="product-card" data-url="{{ product.image_url }}">
                        <div class="product-image">
                            <img src="{{ product.image.url }}" alt="{{ product.description }}">
                            <div class="product-info">
                                <p class="description">{{ product.description }}</p>
                                {% if product.price %}
                                    <p class="price">{{ product.price }} {{ product.currency }}</p>
                                {% endif %}
                                <!-- Star button for favorites -->
                                {% if user.is_authenticated %}
                                    <form method="post" action="{% url 'user:add-to-favorite-ar' product.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="favorites-button" title="إضافة إلى المفضلة">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                                <path d="M12 .587l3.668 7.568 8.332 1.203-6.002 5.838 1.415 8.23L12 18.896l-7.413 3.891 1.415-8.23-6.002-5.838 8.332-1.203z" fill="gold"/>
                                            </svg>
                                        </button>
                                    </form>
                                {% endif %}
                                <div class="button-container">
                                    <form method="get" action="{% url 'fetch-recommended-products-ar' %}">
                                        <input type="hidden" name="product_id" value="{{ product.id }}">
                                        <button type="submit" class="visit-store-button also-button also-ar" title="توصيات">أيضًا</button>
                                    </form>
                                    <a class="visit-store-button store-ar" href="{{ product.product_url }}" target="_blank">المتجر</a>
                                </div>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% include 'pagination_ar.html' %}
        {% endif %}
    </div>

    <!-- Additional Modals -->
    <div id="modal2" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form method="get" action="{% url 'product-list-ar' %}" dir="rtl">
                <h3 class="modal-heading">منتجات معينة</h3>
                <p>تم ترتيب المنتجات بالفعل بترتيب تصاعدي.</p>
                <input type="text" name="q" value="{{ search_query }}" placeholder="البحث عن المنتجات، العلامات التجارية، الألوان..." dir="rtl">
                <label for="priceRange" style="display: block; text-align: right;">نطاق السعر</label>
                <input type="range" id="priceRange" name="max_price" min="0" max="{{ max_price_db }}" value="{{ max_price|default_if_none:max_price_db }}" oninput="updatePriceOutput(this.value)" dir="rtl">
                <output id="priceOutput" for="priceRange" dir="rtl">{{ max_price|default_if_none:max_price_db }} ج.م</output>
                <button type="submit">بحث</button>
            </form>
        </div>
    </div>

    <div id="modal3" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="margin-top: 50px;" dir="rtl">
                مرحبًا بكم في <span style="color: #014421; font-weight: bold;">fromsifr.com</span> !
            </p>
            <p dir="rtl">
                في هذا الإصدار الأول، نقدم مجموعة واسعة من الساعات الذكية من عدة مواقع. <br>
                قريبًا، سنضيف الساعات التقليدية وميزات جديدة...
            </p>
        </div>
    </div>

    <div id="modal4" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="margin-top: 50px;">
                نريد الحصول على ملاحظاتكم!
            </p>
            <p>
                هل لديكم أفكار أو طلبات ميزات؟ <br> هل ترغبون في رؤية منتجات إضافية أو حتى ميزات الشراء والبيع؟<br> نقدر آرائكم ونود سماعها! <br>
                 يرجى مراسلتنا على <strong>medlao.contact@gmail.com</strong><br> أو خذوا لحظة لكتابة منشور لمشاركة ملاحظاتكم.
            </p>
            <p>
                شكرًا لمساعدتكم في تحسين تجربتنا!
            </p>
        </div>
    </div>

    <div id="modal-account" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <img src="{{ user.profile.image.url }}" alt="{{ user.username }} صورة الملف الشخصي" class="profile-image">
            <p id="username">{{ user.username }}</p>
            <p class="email-address">{{ user.email }}</p>
            <ul class="provider-list">
                <li class="provider-item"><a href="{% url 'user:favorites-list-ar' %}" class="provider-link">المفضلات الخاصة بي</a></li>
                <li class="provider-item"><a href="{% url 'account_logout' %}" class="provider-link">تسجيل الخروج</a></li>
                <li class="provider-item"><a href="{% url 'account_change_password' %}" class="provider-link">تغيير كلمة المرور</a></li>
                <li class="provider-item"><a href="{% url 'account_email' %}" class="provider-link">إدارة البريد الإلكتروني</a></li>
            </ul>
        </div>
    </div>

    <script src="{% static 'js/main.js' %}"></script>
    <script>
        function updatePriceOutput(value) {
            document.getElementById('priceOutput').value = value;
        }
    </script>
</body>
</html>